<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260228120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Seed grape catalog from CSV with name and color';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform,
            'Migration can only be executed safely on PostgreSQL.'
        );

        $this->addSql(<<<'SQL'
INSERT INTO grape (name, color)
VALUES
  ('Chardonnay', 'white'::grape_color),
  ('Sauvignon Blanc', 'white'::grape_color),
  ('Riesling', 'white'::grape_color),
  ('Pinot Gris', 'white'::grape_color),
  ('Pinot Grigio', 'white'::grape_color),
  ('Chenin Blanc', 'white'::grape_color),
  ('Sémillon', 'white'::grape_color),
  ('Viognier', 'white'::grape_color),
  ('Gewürztraminer', 'white'::grape_color),
  ('Muscat Blanc à Petits Grains', 'white'::grape_color),
  ('Moscatel de Alejandría', 'white'::grape_color),
  ('Grüner Veltliner', 'white'::grape_color),
  ('Pinot Blanc', 'white'::grape_color),
  ('Colombard', 'white'::grape_color),
  ('Ugni Blanc', 'white'::grape_color),
  ('Trebbiano Toscano', 'white'::grape_color),
  ('Vermentino', 'white'::grape_color),
  ('Marsanne', 'white'::grape_color),
  ('Roussanne', 'white'::grape_color),
  ('Airén', 'white'::grape_color),
  ('Macabeo', 'white'::grape_color),
  ('Viura', 'white'::grape_color),
  ('Xarel·lo', 'white'::grape_color),
  ('Parellada', 'white'::grape_color),
  ('Albariño', 'white'::grape_color),
  ('Alvarinho', 'white'::grape_color),
  ('Verdejo', 'white'::grape_color),
  ('Godello', 'white'::grape_color),
  ('Treixadura', 'white'::grape_color),
  ('Palomino Fino', 'white'::grape_color),
  ('Pedro Ximénez', 'white'::grape_color),
  ('Malvasía', 'white'::grape_color),
  ('Loureiro', 'white'::grape_color),
  ('Arinto', 'white'::grape_color),
  ('Fernão Pires', 'white'::grape_color),
  ('Encruzado', 'white'::grape_color),
  ('Antão Vaz', 'white'::grape_color),
  ('Glera', 'white'::grape_color),
  ('Garganega', 'white'::grape_color),
  ('Verdicchio', 'white'::grape_color),
  ('Falanghina', 'white'::grape_color),
  ('Fiano', 'white'::grape_color),
  ('Greco', 'white'::grape_color),
  ('Arneis', 'white'::grape_color),
  ('Cortese', 'white'::grape_color),
  ('Catarratto', 'white'::grape_color),
  ('Grillo', 'white'::grape_color),
  ('Inzolia', 'white'::grape_color),
  ('Carricante', 'white'::grape_color),
  ('Furmint', 'white'::grape_color),
  ('Hárslevelű', 'white'::grape_color),
  ('Müller-Thurgau', 'white'::grape_color),
  ('Silvaner', 'white'::grape_color),
  ('Assyrtiko', 'white'::grape_color),
  ('Rkatsiteli', 'white'::grape_color),
  ('Torrontés', 'white'::grape_color),
  ('Cabernet Sauvignon', 'red'::grape_color),
  ('Merlot', 'red'::grape_color),
  ('Syrah', 'red'::grape_color),
  ('Shiraz', 'red'::grape_color),
  ('Pinot Noir', 'red'::grape_color),
  ('Grenache', 'red'::grape_color),
  ('Garnacha', 'red'::grape_color),
  ('Tempranillo', 'red'::grape_color),
  ('Cabernet Franc', 'red'::grape_color),
  ('Malbec', 'red'::grape_color),
  ('Zinfandel', 'red'::grape_color),
  ('Primitivo', 'red'::grape_color),
  ('Sangiovese', 'red'::grape_color),
  ('Nebbiolo', 'red'::grape_color),
  ('Carménère', 'red'::grape_color),
  ('Petit Verdot', 'red'::grape_color),
  ('Mourvèdre', 'red'::grape_color),
  ('Monastrell', 'red'::grape_color),
  ('Cinsault', 'red'::grape_color),
  ('Carignan', 'red'::grape_color),
  ('Mazuelo', 'red'::grape_color),
  ('Gamay', 'red'::grape_color),
  ('Bobal', 'red'::grape_color),
  ('Mencía', 'red'::grape_color),
  ('Graciano', 'red'::grape_color),
  ('Prieto Picudo', 'red'::grape_color),
  ('Touriga Nacional', 'red'::grape_color),
  ('Touriga Franca', 'red'::grape_color),
  ('Tinta Roriz', 'red'::grape_color),
  ('Baga', 'red'::grape_color),
  ('Alicante Bouschet', 'red'::grape_color),
  ('Montepulciano', 'red'::grape_color),
  ('Barbera', 'red'::grape_color),
  ('Nero d’Avola', 'red'::grape_color),
  ('Aglianico', 'red'::grape_color),
  ('Corvina', 'red'::grape_color),
  ('Dolcetto', 'red'::grape_color),
  ('Lambrusco', 'red'::grape_color),
  ('Teroldego', 'red'::grape_color),
  ('Lagrein', 'red'::grape_color),
  ('Nerello Mascalese', 'red'::grape_color),
  ('Blaufränkisch', 'red'::grape_color),
  ('Zweigelt', 'red'::grape_color),
  ('Plavac Mali', 'red'::grape_color),
  ('Xinomavro', 'red'::grape_color),
  ('Agiorgitiko', 'red'::grape_color),
  ('Saperavi', 'red'::grape_color),
  ('Pinotage', 'red'::grape_color),
  ('País', 'red'::grape_color),
  ('Listán Prieto', 'red'::grape_color),
  ('Bonarda', 'red'::grape_color),
  ('Petite Sirah', 'red'::grape_color),
  ('Durif', 'red'::grape_color),
  ('Tannat', 'red'::grape_color),
  ('Tibouren', 'red'::grape_color)
ON CONFLICT (name)
DO UPDATE SET
  color = EXCLUDED.color
SQL);
    }

    public function down(Schema $schema): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform,
            'Migration can only be executed safely on PostgreSQL.'
        );

        $this->addSql(<<<'SQL'
DELETE FROM grape
WHERE name IN (
  'Chardonnay',
  'Sauvignon Blanc',
  'Riesling',
  'Pinot Gris',
  'Pinot Grigio',
  'Chenin Blanc',
  'Sémillon',
  'Viognier',
  'Gewürztraminer',
  'Muscat Blanc à Petits Grains',
  'Moscatel de Alejandría',
  'Grüner Veltliner',
  'Pinot Blanc',
  'Colombard',
  'Ugni Blanc',
  'Trebbiano Toscano',
  'Vermentino',
  'Marsanne',
  'Roussanne',
  'Airén',
  'Macabeo',
  'Viura',
  'Xarel·lo',
  'Parellada',
  'Albariño',
  'Alvarinho',
  'Verdejo',
  'Godello',
  'Treixadura',
  'Palomino Fino',
  'Pedro Ximénez',
  'Malvasía',
  'Loureiro',
  'Arinto',
  'Fernão Pires',
  'Encruzado',
  'Antão Vaz',
  'Glera',
  'Garganega',
  'Verdicchio',
  'Falanghina',
  'Fiano',
  'Greco',
  'Arneis',
  'Cortese',
  'Catarratto',
  'Grillo',
  'Inzolia',
  'Carricante',
  'Furmint',
  'Hárslevelű',
  'Müller-Thurgau',
  'Silvaner',
  'Assyrtiko',
  'Rkatsiteli',
  'Torrontés',
  'Cabernet Sauvignon',
  'Merlot',
  'Syrah',
  'Shiraz',
  'Pinot Noir',
  'Grenache',
  'Garnacha',
  'Tempranillo',
  'Cabernet Franc',
  'Malbec',
  'Zinfandel',
  'Primitivo',
  'Sangiovese',
  'Nebbiolo',
  'Carménère',
  'Petit Verdot',
  'Mourvèdre',
  'Monastrell',
  'Cinsault',
  'Carignan',
  'Mazuelo',
  'Gamay',
  'Bobal',
  'Mencía',
  'Graciano',
  'Prieto Picudo',
  'Touriga Nacional',
  'Touriga Franca',
  'Tinta Roriz',
  'Baga',
  'Alicante Bouschet',
  'Montepulciano',
  'Barbera',
  'Nero d’Avola',
  'Aglianico',
  'Corvina',
  'Dolcetto',
  'Lambrusco',
  'Teroldego',
  'Lagrein',
  'Nerello Mascalese',
  'Blaufränkisch',
  'Zweigelt',
  'Plavac Mali',
  'Xinomavro',
  'Agiorgitiko',
  'Saperavi',
  'Pinotage',
  'País',
  'Listán Prieto',
  'Bonarda',
  'Petite Sirah',
  'Durif',
  'Tannat',
  'Tibouren'
)
SQL);
    }
}
