FROM node:22-alpine AS builder

WORKDIR /app
COPY apps/web-public/package*.json ./
RUN npm ci
COPY apps/web-public/ ./
COPY shared/public /shared/public
RUN npm run build

FROM nginx:1.27-alpine
COPY apps/web-public/nginx.prod.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80
