memory_limit=512M
date.timezone=Europe/Madrid
max_execution_time=300
default_socket_timeout=300

upload_max_filesize=20M
post_max_size=20M

opcache.enable=1
opcache.validate_timestamps=1
opcache.revalidate_freq=0
